// Code generated by qtc from "apikey.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/repository/pg/query/apikey.qtpl:1
package query

//line internal/repository/pg/query/apikey.qtpl:3
import "strings"

//line internal/repository/pg/query/apikey.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/repository/pg/query/apikey.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/repository/pg/query/apikey.qtpl:5
func StreamInsertAPIKey(qw422016 *qt422016.Writer, apiKeyID, tenantID, serviceName, keyPrefix, keyHash string, permissions []string, createdBy string, expiresAt *string) {
//line internal/repository/pg/query/apikey.qtpl:5
	qw422016.N().S(`
INSERT INTO api_keys (
    api_key_id,
    tenant_id,
    service_name,
    key_prefix,
    key_hash,
    permissions,
    created_by,
    expires_at,
    is_active,
    created_at
)
VALUES (
    `)
//line internal/repository/pg/query/apikey.qtpl:19
	qw422016.E().S(apiKeyID)
//line internal/repository/pg/query/apikey.qtpl:19
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/apikey.qtpl:20
	qw422016.E().S(tenantID)
//line internal/repository/pg/query/apikey.qtpl:20
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/apikey.qtpl:21
	qw422016.E().S(serviceName)
//line internal/repository/pg/query/apikey.qtpl:21
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/apikey.qtpl:22
	qw422016.E().S(keyPrefix)
//line internal/repository/pg/query/apikey.qtpl:22
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/apikey.qtpl:23
	qw422016.E().S(keyHash)
//line internal/repository/pg/query/apikey.qtpl:23
	qw422016.N().S(`,
    '{`)
//line internal/repository/pg/query/apikey.qtpl:24
	qw422016.E().S(strings.Join(permissions, ","))
//line internal/repository/pg/query/apikey.qtpl:24
	qw422016.N().S(`}',
    `)
//line internal/repository/pg/query/apikey.qtpl:25
	qw422016.E().S(createdBy)
//line internal/repository/pg/query/apikey.qtpl:25
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/apikey.qtpl:26
	if expiresAt != nil {
//line internal/repository/pg/query/apikey.qtpl:26
		qw422016.E().S(*expiresAt)
//line internal/repository/pg/query/apikey.qtpl:26
		qw422016.N().S(`::TIMESTAMPTZ`)
//line internal/repository/pg/query/apikey.qtpl:26
	} else {
//line internal/repository/pg/query/apikey.qtpl:26
		qw422016.N().S(`NULL`)
//line internal/repository/pg/query/apikey.qtpl:26
	}
//line internal/repository/pg/query/apikey.qtpl:26
	qw422016.N().S(`,
    TRUE,
    NOW()
)
RETURNING created_at
`)
//line internal/repository/pg/query/apikey.qtpl:31
}

//line internal/repository/pg/query/apikey.qtpl:31
func WriteInsertAPIKey(qq422016 qtio422016.Writer, apiKeyID, tenantID, serviceName, keyPrefix, keyHash string, permissions []string, createdBy string, expiresAt *string) {
//line internal/repository/pg/query/apikey.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/apikey.qtpl:31
	StreamInsertAPIKey(qw422016, apiKeyID, tenantID, serviceName, keyPrefix, keyHash, permissions, createdBy, expiresAt)
//line internal/repository/pg/query/apikey.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/apikey.qtpl:31
}

//line internal/repository/pg/query/apikey.qtpl:31
func InsertAPIKey(apiKeyID, tenantID, serviceName, keyPrefix, keyHash string, permissions []string, createdBy string, expiresAt *string) string {
//line internal/repository/pg/query/apikey.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/apikey.qtpl:31
	WriteInsertAPIKey(qb422016, apiKeyID, tenantID, serviceName, keyPrefix, keyHash, permissions, createdBy, expiresAt)
//line internal/repository/pg/query/apikey.qtpl:31
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/apikey.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/apikey.qtpl:31
	return qs422016
//line internal/repository/pg/query/apikey.qtpl:31
}

//line internal/repository/pg/query/apikey.qtpl:33
func StreamSelectAPIKeyByID(qw422016 *qt422016.Writer, apiKeyID string) {
//line internal/repository/pg/query/apikey.qtpl:33
	qw422016.N().S(`
SELECT api_key_id,
       tenant_id,
       service_name,
       key_prefix,
       key_hash,
       permissions,
       created_by,
       expires_at,
       is_active,
       created_at
FROM api_keys
WHERE api_key_id = `)
//line internal/repository/pg/query/apikey.qtpl:45
	qw422016.E().S(apiKeyID)
//line internal/repository/pg/query/apikey.qtpl:45
	qw422016.N().S(`
`)
//line internal/repository/pg/query/apikey.qtpl:46
}

//line internal/repository/pg/query/apikey.qtpl:46
func WriteSelectAPIKeyByID(qq422016 qtio422016.Writer, apiKeyID string) {
//line internal/repository/pg/query/apikey.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/apikey.qtpl:46
	StreamSelectAPIKeyByID(qw422016, apiKeyID)
//line internal/repository/pg/query/apikey.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/apikey.qtpl:46
}

//line internal/repository/pg/query/apikey.qtpl:46
func SelectAPIKeyByID(apiKeyID string) string {
//line internal/repository/pg/query/apikey.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/apikey.qtpl:46
	WriteSelectAPIKeyByID(qb422016, apiKeyID)
//line internal/repository/pg/query/apikey.qtpl:46
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/apikey.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/apikey.qtpl:46
	return qs422016
//line internal/repository/pg/query/apikey.qtpl:46
}

//line internal/repository/pg/query/apikey.qtpl:48
func StreamSelectAPIKeyByHash(qw422016 *qt422016.Writer, keyHash string) {
//line internal/repository/pg/query/apikey.qtpl:48
	qw422016.N().S(`
SELECT api_key_id,
       tenant_id,
       service_name,
       key_prefix,
       key_hash,
       permissions,
       created_by,
       expires_at,
       is_active,
       created_at
FROM api_keys
WHERE key_hash  = `)
//line internal/repository/pg/query/apikey.qtpl:60
	qw422016.E().S(keyHash)
//line internal/repository/pg/query/apikey.qtpl:60
	qw422016.N().S(`
  AND is_active = TRUE
`)
//line internal/repository/pg/query/apikey.qtpl:62
}

//line internal/repository/pg/query/apikey.qtpl:62
func WriteSelectAPIKeyByHash(qq422016 qtio422016.Writer, keyHash string) {
//line internal/repository/pg/query/apikey.qtpl:62
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/apikey.qtpl:62
	StreamSelectAPIKeyByHash(qw422016, keyHash)
//line internal/repository/pg/query/apikey.qtpl:62
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/apikey.qtpl:62
}

//line internal/repository/pg/query/apikey.qtpl:62
func SelectAPIKeyByHash(keyHash string) string {
//line internal/repository/pg/query/apikey.qtpl:62
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/apikey.qtpl:62
	WriteSelectAPIKeyByHash(qb422016, keyHash)
//line internal/repository/pg/query/apikey.qtpl:62
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/apikey.qtpl:62
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/apikey.qtpl:62
	return qs422016
//line internal/repository/pg/query/apikey.qtpl:62
}

//line internal/repository/pg/query/apikey.qtpl:64
func StreamSelectAPIKeys(qw422016 *qt422016.Writer, page, pageSize int) {
//line internal/repository/pg/query/apikey.qtpl:64
	qw422016.N().S(`
SELECT api_key_id,
       tenant_id,
       service_name,
       key_prefix,
       key_hash,
       permissions,
       created_by,
       expires_at,
       is_active,
       created_at
FROM api_keys
ORDER BY created_at DESC
LIMIT `)
//line internal/repository/pg/query/apikey.qtpl:77
	qw422016.N().D(pageSize)
//line internal/repository/pg/query/apikey.qtpl:77
	qw422016.N().S(`
OFFSET `)
//line internal/repository/pg/query/apikey.qtpl:78
	qw422016.N().D((page - 1) * pageSize)
//line internal/repository/pg/query/apikey.qtpl:78
	qw422016.N().S(`
`)
//line internal/repository/pg/query/apikey.qtpl:79
}

//line internal/repository/pg/query/apikey.qtpl:79
func WriteSelectAPIKeys(qq422016 qtio422016.Writer, page, pageSize int) {
//line internal/repository/pg/query/apikey.qtpl:79
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/apikey.qtpl:79
	StreamSelectAPIKeys(qw422016, page, pageSize)
//line internal/repository/pg/query/apikey.qtpl:79
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/apikey.qtpl:79
}

//line internal/repository/pg/query/apikey.qtpl:79
func SelectAPIKeys(page, pageSize int) string {
//line internal/repository/pg/query/apikey.qtpl:79
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/apikey.qtpl:79
	WriteSelectAPIKeys(qb422016, page, pageSize)
//line internal/repository/pg/query/apikey.qtpl:79
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/apikey.qtpl:79
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/apikey.qtpl:79
	return qs422016
//line internal/repository/pg/query/apikey.qtpl:79
}

//line internal/repository/pg/query/apikey.qtpl:81
func StreamCountAPIKeys(qw422016 *qt422016.Writer) {
//line internal/repository/pg/query/apikey.qtpl:81
	qw422016.N().S(`
SELECT COUNT(*) AS total
FROM api_keys
`)
//line internal/repository/pg/query/apikey.qtpl:84
}

//line internal/repository/pg/query/apikey.qtpl:84
func WriteCountAPIKeys(qq422016 qtio422016.Writer) {
//line internal/repository/pg/query/apikey.qtpl:84
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/apikey.qtpl:84
	StreamCountAPIKeys(qw422016)
//line internal/repository/pg/query/apikey.qtpl:84
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/apikey.qtpl:84
}

//line internal/repository/pg/query/apikey.qtpl:84
func CountAPIKeys() string {
//line internal/repository/pg/query/apikey.qtpl:84
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/apikey.qtpl:84
	WriteCountAPIKeys(qb422016)
//line internal/repository/pg/query/apikey.qtpl:84
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/apikey.qtpl:84
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/apikey.qtpl:84
	return qs422016
//line internal/repository/pg/query/apikey.qtpl:84
}

//line internal/repository/pg/query/apikey.qtpl:86
func StreamRevokeAPIKey(qw422016 *qt422016.Writer, apiKeyID string) {
//line internal/repository/pg/query/apikey.qtpl:86
	qw422016.N().S(`
UPDATE api_keys
SET is_active = FALSE
WHERE api_key_id = `)
//line internal/repository/pg/query/apikey.qtpl:89
	qw422016.E().S(apiKeyID)
//line internal/repository/pg/query/apikey.qtpl:89
	qw422016.N().S(`
`)
//line internal/repository/pg/query/apikey.qtpl:90
}

//line internal/repository/pg/query/apikey.qtpl:90
func WriteRevokeAPIKey(qq422016 qtio422016.Writer, apiKeyID string) {
//line internal/repository/pg/query/apikey.qtpl:90
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/apikey.qtpl:90
	StreamRevokeAPIKey(qw422016, apiKeyID)
//line internal/repository/pg/query/apikey.qtpl:90
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/apikey.qtpl:90
}

//line internal/repository/pg/query/apikey.qtpl:90
func RevokeAPIKey(apiKeyID string) string {
//line internal/repository/pg/query/apikey.qtpl:90
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/apikey.qtpl:90
	WriteRevokeAPIKey(qb422016, apiKeyID)
//line internal/repository/pg/query/apikey.qtpl:90
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/apikey.qtpl:90
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/apikey.qtpl:90
	return qs422016
//line internal/repository/pg/query/apikey.qtpl:90
}
