// Code generated by qtc from "password.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/repository/pg/query/password.qtpl:1
package query

//line internal/repository/pg/query/password.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/repository/pg/query/password.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/repository/pg/query/password.qtpl:3
func StreamInsertPassword(qw422016 *qt422016.Writer, userID, passwordHash string) {
//line internal/repository/pg/query/password.qtpl:3
	qw422016.N().S(`
INSERT INTO user_password_hash (
    user_id,
    password_hash,
    created_at,
    updated_at
)
VALUES (
    `)
//line internal/repository/pg/query/password.qtpl:11
	qw422016.E().S(userID)
//line internal/repository/pg/query/password.qtpl:11
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/password.qtpl:12
	qw422016.E().S(passwordHash)
//line internal/repository/pg/query/password.qtpl:12
	qw422016.N().S(`,
    NOW(),
    NULL
)
`)
//line internal/repository/pg/query/password.qtpl:16
}

//line internal/repository/pg/query/password.qtpl:16
func WriteInsertPassword(qq422016 qtio422016.Writer, userID, passwordHash string) {
//line internal/repository/pg/query/password.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/password.qtpl:16
	StreamInsertPassword(qw422016, userID, passwordHash)
//line internal/repository/pg/query/password.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/password.qtpl:16
}

//line internal/repository/pg/query/password.qtpl:16
func InsertPassword(userID, passwordHash string) string {
//line internal/repository/pg/query/password.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/password.qtpl:16
	WriteInsertPassword(qb422016, userID, passwordHash)
//line internal/repository/pg/query/password.qtpl:16
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/password.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/password.qtpl:16
	return qs422016
//line internal/repository/pg/query/password.qtpl:16
}

//line internal/repository/pg/query/password.qtpl:18
func StreamSelectPasswordByUserID(qw422016 *qt422016.Writer, userID string) {
//line internal/repository/pg/query/password.qtpl:18
	qw422016.N().S(`
SELECT password_hash
FROM user_password_hash
WHERE user_id = `)
//line internal/repository/pg/query/password.qtpl:21
	qw422016.E().S(userID)
//line internal/repository/pg/query/password.qtpl:21
	qw422016.N().S(`
`)
//line internal/repository/pg/query/password.qtpl:22
}

//line internal/repository/pg/query/password.qtpl:22
func WriteSelectPasswordByUserID(qq422016 qtio422016.Writer, userID string) {
//line internal/repository/pg/query/password.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/password.qtpl:22
	StreamSelectPasswordByUserID(qw422016, userID)
//line internal/repository/pg/query/password.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/password.qtpl:22
}

//line internal/repository/pg/query/password.qtpl:22
func SelectPasswordByUserID(userID string) string {
//line internal/repository/pg/query/password.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/password.qtpl:22
	WriteSelectPasswordByUserID(qb422016, userID)
//line internal/repository/pg/query/password.qtpl:22
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/password.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/password.qtpl:22
	return qs422016
//line internal/repository/pg/query/password.qtpl:22
}

//line internal/repository/pg/query/password.qtpl:24
func StreamUpdatePassword(qw422016 *qt422016.Writer, userID, passwordHash string) {
//line internal/repository/pg/query/password.qtpl:24
	qw422016.N().S(`
UPDATE user_password_hash
SET password_hash = `)
//line internal/repository/pg/query/password.qtpl:26
	qw422016.E().S(passwordHash)
//line internal/repository/pg/query/password.qtpl:26
	qw422016.N().S(`,
    updated_at    = NOW()
WHERE user_id = `)
//line internal/repository/pg/query/password.qtpl:28
	qw422016.E().S(userID)
//line internal/repository/pg/query/password.qtpl:28
	qw422016.N().S(`
`)
//line internal/repository/pg/query/password.qtpl:29
}

//line internal/repository/pg/query/password.qtpl:29
func WriteUpdatePassword(qq422016 qtio422016.Writer, userID, passwordHash string) {
//line internal/repository/pg/query/password.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/password.qtpl:29
	StreamUpdatePassword(qw422016, userID, passwordHash)
//line internal/repository/pg/query/password.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/password.qtpl:29
}

//line internal/repository/pg/query/password.qtpl:29
func UpdatePassword(userID, passwordHash string) string {
//line internal/repository/pg/query/password.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/password.qtpl:29
	WriteUpdatePassword(qb422016, userID, passwordHash)
//line internal/repository/pg/query/password.qtpl:29
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/password.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/password.qtpl:29
	return qs422016
//line internal/repository/pg/query/password.qtpl:29
}
