// Code generated by qtc from "role.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/repository/pg/query/role.qtpl:1
package query

//line internal/repository/pg/query/role.qtpl:3
import "strings"

//line internal/repository/pg/query/role.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/repository/pg/query/role.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/repository/pg/query/role.qtpl:5
func StreamInsertRole(qw422016 *qt422016.Writer, roleID, tenantID, name string, permissions []string, isSystem bool, description string) {
//line internal/repository/pg/query/role.qtpl:5
	qw422016.N().S(`
INSERT INTO roles (
    role_id,
    tenant_id,
    name,
    permissions,
    is_system,
    description,
    created_at,
    updated_at
)
VALUES (
    `)
//line internal/repository/pg/query/role.qtpl:17
	qw422016.E().S(roleID)
//line internal/repository/pg/query/role.qtpl:17
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/role.qtpl:18
	qw422016.E().S(tenantID)
//line internal/repository/pg/query/role.qtpl:18
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/role.qtpl:19
	qw422016.E().S(name)
//line internal/repository/pg/query/role.qtpl:19
	qw422016.N().S(`,
    '{`)
//line internal/repository/pg/query/role.qtpl:20
	qw422016.E().S(strings.Join(permissions, ","))
//line internal/repository/pg/query/role.qtpl:20
	qw422016.N().S(`}',
    `)
//line internal/repository/pg/query/role.qtpl:21
	if isSystem {
//line internal/repository/pg/query/role.qtpl:21
		qw422016.N().S(`TRUE`)
//line internal/repository/pg/query/role.qtpl:21
	} else {
//line internal/repository/pg/query/role.qtpl:21
		qw422016.N().S(`FALSE`)
//line internal/repository/pg/query/role.qtpl:21
	}
//line internal/repository/pg/query/role.qtpl:21
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/role.qtpl:22
	qw422016.E().S(description)
//line internal/repository/pg/query/role.qtpl:22
	qw422016.N().S(`,
    NOW(),
    NULL
)
RETURNING created_at
`)
//line internal/repository/pg/query/role.qtpl:27
}

//line internal/repository/pg/query/role.qtpl:27
func WriteInsertRole(qq422016 qtio422016.Writer, roleID, tenantID, name string, permissions []string, isSystem bool, description string) {
//line internal/repository/pg/query/role.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/role.qtpl:27
	StreamInsertRole(qw422016, roleID, tenantID, name, permissions, isSystem, description)
//line internal/repository/pg/query/role.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/role.qtpl:27
}

//line internal/repository/pg/query/role.qtpl:27
func InsertRole(roleID, tenantID, name string, permissions []string, isSystem bool, description string) string {
//line internal/repository/pg/query/role.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/role.qtpl:27
	WriteInsertRole(qb422016, roleID, tenantID, name, permissions, isSystem, description)
//line internal/repository/pg/query/role.qtpl:27
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/role.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/role.qtpl:27
	return qs422016
//line internal/repository/pg/query/role.qtpl:27
}

//line internal/repository/pg/query/role.qtpl:29
func StreamSelectRoleByID(qw422016 *qt422016.Writer, roleID string) {
//line internal/repository/pg/query/role.qtpl:29
	qw422016.N().S(`
SELECT role_id,
       tenant_id,
       name,
       permissions,
       is_system,
       COALESCE(description, '') AS description,
       created_at,
       updated_at
FROM roles
WHERE role_id = `)
//line internal/repository/pg/query/role.qtpl:39
	qw422016.E().S(roleID)
//line internal/repository/pg/query/role.qtpl:39
	qw422016.N().S(`
`)
//line internal/repository/pg/query/role.qtpl:40
}

//line internal/repository/pg/query/role.qtpl:40
func WriteSelectRoleByID(qq422016 qtio422016.Writer, roleID string) {
//line internal/repository/pg/query/role.qtpl:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/role.qtpl:40
	StreamSelectRoleByID(qw422016, roleID)
//line internal/repository/pg/query/role.qtpl:40
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/role.qtpl:40
}

//line internal/repository/pg/query/role.qtpl:40
func SelectRoleByID(roleID string) string {
//line internal/repository/pg/query/role.qtpl:40
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/role.qtpl:40
	WriteSelectRoleByID(qb422016, roleID)
//line internal/repository/pg/query/role.qtpl:40
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/role.qtpl:40
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/role.qtpl:40
	return qs422016
//line internal/repository/pg/query/role.qtpl:40
}

//line internal/repository/pg/query/role.qtpl:42
func StreamSelectRoleByName(qw422016 *qt422016.Writer, tenantID, name string) {
//line internal/repository/pg/query/role.qtpl:42
	qw422016.N().S(`
SELECT role_id,
       tenant_id,
       name,
       permissions,
       is_system,
       COALESCE(description, '') AS description,
       created_at,
       updated_at
FROM roles
WHERE tenant_id = `)
//line internal/repository/pg/query/role.qtpl:52
	qw422016.E().S(tenantID)
//line internal/repository/pg/query/role.qtpl:52
	qw422016.N().S(`
  AND name      = `)
//line internal/repository/pg/query/role.qtpl:53
	qw422016.E().S(name)
//line internal/repository/pg/query/role.qtpl:53
	qw422016.N().S(`
`)
//line internal/repository/pg/query/role.qtpl:54
}

//line internal/repository/pg/query/role.qtpl:54
func WriteSelectRoleByName(qq422016 qtio422016.Writer, tenantID, name string) {
//line internal/repository/pg/query/role.qtpl:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/role.qtpl:54
	StreamSelectRoleByName(qw422016, tenantID, name)
//line internal/repository/pg/query/role.qtpl:54
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/role.qtpl:54
}

//line internal/repository/pg/query/role.qtpl:54
func SelectRoleByName(tenantID, name string) string {
//line internal/repository/pg/query/role.qtpl:54
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/role.qtpl:54
	WriteSelectRoleByName(qb422016, tenantID, name)
//line internal/repository/pg/query/role.qtpl:54
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/role.qtpl:54
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/role.qtpl:54
	return qs422016
//line internal/repository/pg/query/role.qtpl:54
}

//line internal/repository/pg/query/role.qtpl:56
func StreamSelectRoles(qw422016 *qt422016.Writer, page, pageSize int) {
//line internal/repository/pg/query/role.qtpl:56
	qw422016.N().S(`
SELECT role_id,
       tenant_id,
       name,
       permissions,
       is_system,
       COALESCE(description, '') AS description,
       created_at,
       updated_at
FROM roles
ORDER BY created_at DESC
LIMIT `)
//line internal/repository/pg/query/role.qtpl:67
	qw422016.N().D(pageSize)
//line internal/repository/pg/query/role.qtpl:67
	qw422016.N().S(`
OFFSET `)
//line internal/repository/pg/query/role.qtpl:68
	qw422016.N().D((page - 1) * pageSize)
//line internal/repository/pg/query/role.qtpl:68
	qw422016.N().S(`
`)
//line internal/repository/pg/query/role.qtpl:69
}

//line internal/repository/pg/query/role.qtpl:69
func WriteSelectRoles(qq422016 qtio422016.Writer, page, pageSize int) {
//line internal/repository/pg/query/role.qtpl:69
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/role.qtpl:69
	StreamSelectRoles(qw422016, page, pageSize)
//line internal/repository/pg/query/role.qtpl:69
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/role.qtpl:69
}

//line internal/repository/pg/query/role.qtpl:69
func SelectRoles(page, pageSize int) string {
//line internal/repository/pg/query/role.qtpl:69
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/role.qtpl:69
	WriteSelectRoles(qb422016, page, pageSize)
//line internal/repository/pg/query/role.qtpl:69
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/role.qtpl:69
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/role.qtpl:69
	return qs422016
//line internal/repository/pg/query/role.qtpl:69
}

//line internal/repository/pg/query/role.qtpl:71
func StreamCountRoles(qw422016 *qt422016.Writer) {
//line internal/repository/pg/query/role.qtpl:71
	qw422016.N().S(`
SELECT COUNT(*) AS total
FROM roles
`)
//line internal/repository/pg/query/role.qtpl:74
}

//line internal/repository/pg/query/role.qtpl:74
func WriteCountRoles(qq422016 qtio422016.Writer) {
//line internal/repository/pg/query/role.qtpl:74
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/role.qtpl:74
	StreamCountRoles(qw422016)
//line internal/repository/pg/query/role.qtpl:74
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/role.qtpl:74
}

//line internal/repository/pg/query/role.qtpl:74
func CountRoles() string {
//line internal/repository/pg/query/role.qtpl:74
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/role.qtpl:74
	WriteCountRoles(qb422016)
//line internal/repository/pg/query/role.qtpl:74
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/role.qtpl:74
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/role.qtpl:74
	return qs422016
//line internal/repository/pg/query/role.qtpl:74
}

//line internal/repository/pg/query/role.qtpl:76
func StreamUpdateRole(qw422016 *qt422016.Writer, roleID, name string, permissions []string, description string) {
//line internal/repository/pg/query/role.qtpl:76
	qw422016.N().S(`
UPDATE roles
SET name        = `)
//line internal/repository/pg/query/role.qtpl:78
	qw422016.E().S(name)
//line internal/repository/pg/query/role.qtpl:78
	qw422016.N().S(`,
    permissions = '{`)
//line internal/repository/pg/query/role.qtpl:79
	qw422016.E().S(strings.Join(permissions, ","))
//line internal/repository/pg/query/role.qtpl:79
	qw422016.N().S(`}',
    description = `)
//line internal/repository/pg/query/role.qtpl:80
	qw422016.E().S(description)
//line internal/repository/pg/query/role.qtpl:80
	qw422016.N().S(`,
    updated_at  = NOW()
WHERE role_id = `)
//line internal/repository/pg/query/role.qtpl:82
	qw422016.E().S(roleID)
//line internal/repository/pg/query/role.qtpl:82
	qw422016.N().S(`
`)
//line internal/repository/pg/query/role.qtpl:83
}

//line internal/repository/pg/query/role.qtpl:83
func WriteUpdateRole(qq422016 qtio422016.Writer, roleID, name string, permissions []string, description string) {
//line internal/repository/pg/query/role.qtpl:83
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/role.qtpl:83
	StreamUpdateRole(qw422016, roleID, name, permissions, description)
//line internal/repository/pg/query/role.qtpl:83
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/role.qtpl:83
}

//line internal/repository/pg/query/role.qtpl:83
func UpdateRole(roleID, name string, permissions []string, description string) string {
//line internal/repository/pg/query/role.qtpl:83
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/role.qtpl:83
	WriteUpdateRole(qb422016, roleID, name, permissions, description)
//line internal/repository/pg/query/role.qtpl:83
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/role.qtpl:83
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/role.qtpl:83
	return qs422016
//line internal/repository/pg/query/role.qtpl:83
}

//line internal/repository/pg/query/role.qtpl:85
func StreamDeleteRole(qw422016 *qt422016.Writer, roleID string) {
//line internal/repository/pg/query/role.qtpl:85
	qw422016.N().S(`
DELETE FROM roles
WHERE role_id  = `)
//line internal/repository/pg/query/role.qtpl:87
	qw422016.E().S(roleID)
//line internal/repository/pg/query/role.qtpl:87
	qw422016.N().S(`
  AND is_system = FALSE
`)
//line internal/repository/pg/query/role.qtpl:89
}

//line internal/repository/pg/query/role.qtpl:89
func WriteDeleteRole(qq422016 qtio422016.Writer, roleID string) {
//line internal/repository/pg/query/role.qtpl:89
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/role.qtpl:89
	StreamDeleteRole(qw422016, roleID)
//line internal/repository/pg/query/role.qtpl:89
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/role.qtpl:89
}

//line internal/repository/pg/query/role.qtpl:89
func DeleteRole(roleID string) string {
//line internal/repository/pg/query/role.qtpl:89
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/role.qtpl:89
	WriteDeleteRole(qb422016, roleID)
//line internal/repository/pg/query/role.qtpl:89
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/role.qtpl:89
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/role.qtpl:89
	return qs422016
//line internal/repository/pg/query/role.qtpl:89
}

//line internal/repository/pg/query/role.qtpl:91
func StreamAssignRoleToUser(qw422016 *qt422016.Writer, userID, roleID string) {
//line internal/repository/pg/query/role.qtpl:91
	qw422016.N().S(`
INSERT INTO user_roles (user_id, role_id, assigned_at)
VALUES (`)
//line internal/repository/pg/query/role.qtpl:93
	qw422016.E().S(userID)
//line internal/repository/pg/query/role.qtpl:93
	qw422016.N().S(`, `)
//line internal/repository/pg/query/role.qtpl:93
	qw422016.E().S(roleID)
//line internal/repository/pg/query/role.qtpl:93
	qw422016.N().S(`, NOW())
ON CONFLICT (user_id, role_id) DO NOTHING
`)
//line internal/repository/pg/query/role.qtpl:95
}

//line internal/repository/pg/query/role.qtpl:95
func WriteAssignRoleToUser(qq422016 qtio422016.Writer, userID, roleID string) {
//line internal/repository/pg/query/role.qtpl:95
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/role.qtpl:95
	StreamAssignRoleToUser(qw422016, userID, roleID)
//line internal/repository/pg/query/role.qtpl:95
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/role.qtpl:95
}

//line internal/repository/pg/query/role.qtpl:95
func AssignRoleToUser(userID, roleID string) string {
//line internal/repository/pg/query/role.qtpl:95
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/role.qtpl:95
	WriteAssignRoleToUser(qb422016, userID, roleID)
//line internal/repository/pg/query/role.qtpl:95
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/role.qtpl:95
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/role.qtpl:95
	return qs422016
//line internal/repository/pg/query/role.qtpl:95
}

//line internal/repository/pg/query/role.qtpl:97
func StreamRevokeRoleFromUser(qw422016 *qt422016.Writer, userID, roleID string) {
//line internal/repository/pg/query/role.qtpl:97
	qw422016.N().S(`
DELETE FROM user_roles
WHERE user_id = `)
//line internal/repository/pg/query/role.qtpl:99
	qw422016.E().S(userID)
//line internal/repository/pg/query/role.qtpl:99
	qw422016.N().S(`
  AND role_id = `)
//line internal/repository/pg/query/role.qtpl:100
	qw422016.E().S(roleID)
//line internal/repository/pg/query/role.qtpl:100
	qw422016.N().S(`
`)
//line internal/repository/pg/query/role.qtpl:101
}

//line internal/repository/pg/query/role.qtpl:101
func WriteRevokeRoleFromUser(qq422016 qtio422016.Writer, userID, roleID string) {
//line internal/repository/pg/query/role.qtpl:101
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/role.qtpl:101
	StreamRevokeRoleFromUser(qw422016, userID, roleID)
//line internal/repository/pg/query/role.qtpl:101
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/role.qtpl:101
}

//line internal/repository/pg/query/role.qtpl:101
func RevokeRoleFromUser(userID, roleID string) string {
//line internal/repository/pg/query/role.qtpl:101
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/role.qtpl:101
	WriteRevokeRoleFromUser(qb422016, userID, roleID)
//line internal/repository/pg/query/role.qtpl:101
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/role.qtpl:101
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/role.qtpl:101
	return qs422016
//line internal/repository/pg/query/role.qtpl:101
}

//line internal/repository/pg/query/role.qtpl:103
func StreamSelectUserRoles(qw422016 *qt422016.Writer, userID string) {
//line internal/repository/pg/query/role.qtpl:103
	qw422016.N().S(`
SELECT r.role_id,
       r.tenant_id,
       r.name,
       r.permissions,
       r.is_system,
       COALESCE(r.description, '') AS description,
       r.created_at,
       r.updated_at
FROM roles r
JOIN user_roles ur ON r.role_id = ur.role_id
WHERE ur.user_id = `)
//line internal/repository/pg/query/role.qtpl:114
	qw422016.E().S(userID)
//line internal/repository/pg/query/role.qtpl:114
	qw422016.N().S(`
`)
//line internal/repository/pg/query/role.qtpl:115
}

//line internal/repository/pg/query/role.qtpl:115
func WriteSelectUserRoles(qq422016 qtio422016.Writer, userID string) {
//line internal/repository/pg/query/role.qtpl:115
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/role.qtpl:115
	StreamSelectUserRoles(qw422016, userID)
//line internal/repository/pg/query/role.qtpl:115
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/role.qtpl:115
}

//line internal/repository/pg/query/role.qtpl:115
func SelectUserRoles(userID string) string {
//line internal/repository/pg/query/role.qtpl:115
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/role.qtpl:115
	WriteSelectUserRoles(qb422016, userID)
//line internal/repository/pg/query/role.qtpl:115
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/role.qtpl:115
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/role.qtpl:115
	return qs422016
//line internal/repository/pg/query/role.qtpl:115
}

//line internal/repository/pg/query/role.qtpl:117
func StreamCheckUserPermission(qw422016 *qt422016.Writer, userID, permission string) {
//line internal/repository/pg/query/role.qtpl:117
	qw422016.N().S(`
SELECT EXISTS (
    SELECT 1
    FROM user_roles ur
    JOIN roles r ON r.role_id = ur.role_id
    CROSS JOIN LATERAL unnest(r.permissions) AS p(perm)
    WHERE ur.user_id = `)
//line internal/repository/pg/query/role.qtpl:123
	qw422016.E().S(userID)
//line internal/repository/pg/query/role.qtpl:123
	qw422016.N().S(`
      AND p.perm     = `)
//line internal/repository/pg/query/role.qtpl:124
	qw422016.E().S(permission)
//line internal/repository/pg/query/role.qtpl:124
	qw422016.N().S(`
) AS has_permission
`)
//line internal/repository/pg/query/role.qtpl:126
}

//line internal/repository/pg/query/role.qtpl:126
func WriteCheckUserPermission(qq422016 qtio422016.Writer, userID, permission string) {
//line internal/repository/pg/query/role.qtpl:126
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/role.qtpl:126
	StreamCheckUserPermission(qw422016, userID, permission)
//line internal/repository/pg/query/role.qtpl:126
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/role.qtpl:126
}

//line internal/repository/pg/query/role.qtpl:126
func CheckUserPermission(userID, permission string) string {
//line internal/repository/pg/query/role.qtpl:126
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/role.qtpl:126
	WriteCheckUserPermission(qb422016, userID, permission)
//line internal/repository/pg/query/role.qtpl:126
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/role.qtpl:126
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/role.qtpl:126
	return qs422016
//line internal/repository/pg/query/role.qtpl:126
}
