// Code generated by qtc from "session.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/repository/pg/query/session.qtpl:1
package query

//line internal/repository/pg/query/session.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/repository/pg/query/session.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/repository/pg/query/session.qtpl:3
func StreamInsertSession(qw422016 *qt422016.Writer, sessionID, userID string, identityID *string, refreshTokenHash string, deviceInfo, ipAddress *string, expiresAt string) {
//line internal/repository/pg/query/session.qtpl:3
	qw422016.N().S(`
INSERT INTO user_sessions (
    session_id,
    user_id,
    identity_id,
    refresh_token,
    device_info,
    ip_address,
    expires_at,
    created_at,
    revoked_at
)
VALUES (
    `)
//line internal/repository/pg/query/session.qtpl:16
	qw422016.E().S(sessionID)
//line internal/repository/pg/query/session.qtpl:16
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/session.qtpl:17
	qw422016.E().S(userID)
//line internal/repository/pg/query/session.qtpl:17
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/session.qtpl:18
	if identityID != nil {
//line internal/repository/pg/query/session.qtpl:18
		qw422016.E().S(*identityID)
//line internal/repository/pg/query/session.qtpl:18
	} else {
//line internal/repository/pg/query/session.qtpl:18
		qw422016.N().S(`NULL`)
//line internal/repository/pg/query/session.qtpl:18
	}
//line internal/repository/pg/query/session.qtpl:18
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/session.qtpl:19
	qw422016.E().S(refreshTokenHash)
//line internal/repository/pg/query/session.qtpl:19
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/session.qtpl:20
	if deviceInfo != nil {
//line internal/repository/pg/query/session.qtpl:20
		qw422016.E().S(*deviceInfo)
//line internal/repository/pg/query/session.qtpl:20
	} else {
//line internal/repository/pg/query/session.qtpl:20
		qw422016.N().S(`NULL`)
//line internal/repository/pg/query/session.qtpl:20
	}
//line internal/repository/pg/query/session.qtpl:20
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/session.qtpl:21
	if ipAddress != nil {
//line internal/repository/pg/query/session.qtpl:21
		qw422016.E().S(*ipAddress)
//line internal/repository/pg/query/session.qtpl:21
		qw422016.N().S(`::INET`)
//line internal/repository/pg/query/session.qtpl:21
	} else {
//line internal/repository/pg/query/session.qtpl:21
		qw422016.N().S(`NULL`)
//line internal/repository/pg/query/session.qtpl:21
	}
//line internal/repository/pg/query/session.qtpl:21
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/session.qtpl:22
	qw422016.E().S(expiresAt)
//line internal/repository/pg/query/session.qtpl:22
	qw422016.N().S(`::TIMESTAMPTZ,
    NOW(),
    NULL
)
RETURNING created_at
`)
//line internal/repository/pg/query/session.qtpl:27
}

//line internal/repository/pg/query/session.qtpl:27
func WriteInsertSession(qq422016 qtio422016.Writer, sessionID, userID string, identityID *string, refreshTokenHash string, deviceInfo, ipAddress *string, expiresAt string) {
//line internal/repository/pg/query/session.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/session.qtpl:27
	StreamInsertSession(qw422016, sessionID, userID, identityID, refreshTokenHash, deviceInfo, ipAddress, expiresAt)
//line internal/repository/pg/query/session.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/session.qtpl:27
}

//line internal/repository/pg/query/session.qtpl:27
func InsertSession(sessionID, userID string, identityID *string, refreshTokenHash string, deviceInfo, ipAddress *string, expiresAt string) string {
//line internal/repository/pg/query/session.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/session.qtpl:27
	WriteInsertSession(qb422016, sessionID, userID, identityID, refreshTokenHash, deviceInfo, ipAddress, expiresAt)
//line internal/repository/pg/query/session.qtpl:27
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/session.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/session.qtpl:27
	return qs422016
//line internal/repository/pg/query/session.qtpl:27
}

//line internal/repository/pg/query/session.qtpl:29
func StreamSelectSessionByRefreshToken(qw422016 *qt422016.Writer, refreshTokenHash string) {
//line internal/repository/pg/query/session.qtpl:29
	qw422016.N().S(`
SELECT session_id,
       user_id,
       identity_id,
       refresh_token,
       COALESCE(device_info, '') AS device_info,
       ip_address,
       expires_at,
       created_at,
       revoked_at
FROM user_sessions
WHERE refresh_token = `)
//line internal/repository/pg/query/session.qtpl:40
	qw422016.E().S(refreshTokenHash)
//line internal/repository/pg/query/session.qtpl:40
	qw422016.N().S(`
  AND revoked_at    IS NULL
`)
//line internal/repository/pg/query/session.qtpl:42
}

//line internal/repository/pg/query/session.qtpl:42
func WriteSelectSessionByRefreshToken(qq422016 qtio422016.Writer, refreshTokenHash string) {
//line internal/repository/pg/query/session.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/session.qtpl:42
	StreamSelectSessionByRefreshToken(qw422016, refreshTokenHash)
//line internal/repository/pg/query/session.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/session.qtpl:42
}

//line internal/repository/pg/query/session.qtpl:42
func SelectSessionByRefreshToken(refreshTokenHash string) string {
//line internal/repository/pg/query/session.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/session.qtpl:42
	WriteSelectSessionByRefreshToken(qb422016, refreshTokenHash)
//line internal/repository/pg/query/session.qtpl:42
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/session.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/session.qtpl:42
	return qs422016
//line internal/repository/pg/query/session.qtpl:42
}

//line internal/repository/pg/query/session.qtpl:44
func StreamRevokeSession(qw422016 *qt422016.Writer, sessionID string) {
//line internal/repository/pg/query/session.qtpl:44
	qw422016.N().S(`
UPDATE user_sessions
SET revoked_at = NOW()
WHERE session_id = `)
//line internal/repository/pg/query/session.qtpl:47
	qw422016.E().S(sessionID)
//line internal/repository/pg/query/session.qtpl:47
	qw422016.N().S(`
`)
//line internal/repository/pg/query/session.qtpl:48
}

//line internal/repository/pg/query/session.qtpl:48
func WriteRevokeSession(qq422016 qtio422016.Writer, sessionID string) {
//line internal/repository/pg/query/session.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/session.qtpl:48
	StreamRevokeSession(qw422016, sessionID)
//line internal/repository/pg/query/session.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/session.qtpl:48
}

//line internal/repository/pg/query/session.qtpl:48
func RevokeSession(sessionID string) string {
//line internal/repository/pg/query/session.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/session.qtpl:48
	WriteRevokeSession(qb422016, sessionID)
//line internal/repository/pg/query/session.qtpl:48
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/session.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/session.qtpl:48
	return qs422016
//line internal/repository/pg/query/session.qtpl:48
}

//line internal/repository/pg/query/session.qtpl:50
func StreamRevokeAllUserSessions(qw422016 *qt422016.Writer, userID string) {
//line internal/repository/pg/query/session.qtpl:50
	qw422016.N().S(`
UPDATE user_sessions
SET revoked_at = NOW()
WHERE user_id    = `)
//line internal/repository/pg/query/session.qtpl:53
	qw422016.E().S(userID)
//line internal/repository/pg/query/session.qtpl:53
	qw422016.N().S(`
  AND revoked_at IS NULL
`)
//line internal/repository/pg/query/session.qtpl:55
}

//line internal/repository/pg/query/session.qtpl:55
func WriteRevokeAllUserSessions(qq422016 qtio422016.Writer, userID string) {
//line internal/repository/pg/query/session.qtpl:55
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/session.qtpl:55
	StreamRevokeAllUserSessions(qw422016, userID)
//line internal/repository/pg/query/session.qtpl:55
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/session.qtpl:55
}

//line internal/repository/pg/query/session.qtpl:55
func RevokeAllUserSessions(userID string) string {
//line internal/repository/pg/query/session.qtpl:55
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/session.qtpl:55
	WriteRevokeAllUserSessions(qb422016, userID)
//line internal/repository/pg/query/session.qtpl:55
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/session.qtpl:55
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/session.qtpl:55
	return qs422016
//line internal/repository/pg/query/session.qtpl:55
}
