// Code generated by qtc from "user.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/repository/pg/query/user.qtpl:1
package query

//line internal/repository/pg/query/user.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/repository/pg/query/user.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/repository/pg/query/user.qtpl:3
func StreamInsertUser(qw422016 *qt422016.Writer, userID, tenantID, login, displayName, emailPrimary, locale, timezone string) {
//line internal/repository/pg/query/user.qtpl:3
	qw422016.N().S(`
INSERT INTO users (
    user_id,
    tenant_id,
    login,
    display_name,
    email_primary,
    locale,
    timezone,
    created_at,
    updated_at,
    is_active
)
VALUES (
    `)
//line internal/repository/pg/query/user.qtpl:17
	qw422016.E().S(userID)
//line internal/repository/pg/query/user.qtpl:17
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/user.qtpl:18
	qw422016.E().S(tenantID)
//line internal/repository/pg/query/user.qtpl:18
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/user.qtpl:19
	qw422016.E().S(login)
//line internal/repository/pg/query/user.qtpl:19
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/user.qtpl:20
	qw422016.E().S(displayName)
//line internal/repository/pg/query/user.qtpl:20
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/user.qtpl:21
	qw422016.E().S(emailPrimary)
//line internal/repository/pg/query/user.qtpl:21
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/user.qtpl:22
	qw422016.E().S(locale)
//line internal/repository/pg/query/user.qtpl:22
	qw422016.N().S(`,
    `)
//line internal/repository/pg/query/user.qtpl:23
	qw422016.E().S(timezone)
//line internal/repository/pg/query/user.qtpl:23
	qw422016.N().S(`,
    NOW(),
    NULL,
    TRUE
)
RETURNING created_at
`)
//line internal/repository/pg/query/user.qtpl:29
}

//line internal/repository/pg/query/user.qtpl:29
func WriteInsertUser(qq422016 qtio422016.Writer, userID, tenantID, login, displayName, emailPrimary, locale, timezone string) {
//line internal/repository/pg/query/user.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/user.qtpl:29
	StreamInsertUser(qw422016, userID, tenantID, login, displayName, emailPrimary, locale, timezone)
//line internal/repository/pg/query/user.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/user.qtpl:29
}

//line internal/repository/pg/query/user.qtpl:29
func InsertUser(userID, tenantID, login, displayName, emailPrimary, locale, timezone string) string {
//line internal/repository/pg/query/user.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/user.qtpl:29
	WriteInsertUser(qb422016, userID, tenantID, login, displayName, emailPrimary, locale, timezone)
//line internal/repository/pg/query/user.qtpl:29
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/user.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/user.qtpl:29
	return qs422016
//line internal/repository/pg/query/user.qtpl:29
}

//line internal/repository/pg/query/user.qtpl:31
func StreamSelectUserByID(qw422016 *qt422016.Writer, userID string) {
//line internal/repository/pg/query/user.qtpl:31
	qw422016.N().S(`
SELECT user_id,
       tenant_id,
       login,
       COALESCE(display_name, '') AS display_name,
       email_primary,
       COALESCE(locale, '')       AS locale,
       COALESCE(timezone, '')     AS timezone,
       is_active,
       created_at,
       updated_at
FROM users
WHERE user_id = `)
//line internal/repository/pg/query/user.qtpl:43
	qw422016.E().S(userID)
//line internal/repository/pg/query/user.qtpl:43
	qw422016.N().S(`
`)
//line internal/repository/pg/query/user.qtpl:44
}

//line internal/repository/pg/query/user.qtpl:44
func WriteSelectUserByID(qq422016 qtio422016.Writer, userID string) {
//line internal/repository/pg/query/user.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/user.qtpl:44
	StreamSelectUserByID(qw422016, userID)
//line internal/repository/pg/query/user.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/user.qtpl:44
}

//line internal/repository/pg/query/user.qtpl:44
func SelectUserByID(userID string) string {
//line internal/repository/pg/query/user.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/user.qtpl:44
	WriteSelectUserByID(qb422016, userID)
//line internal/repository/pg/query/user.qtpl:44
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/user.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/user.qtpl:44
	return qs422016
//line internal/repository/pg/query/user.qtpl:44
}

//line internal/repository/pg/query/user.qtpl:46
func StreamSelectUserByLogin(qw422016 *qt422016.Writer, login string) {
//line internal/repository/pg/query/user.qtpl:46
	qw422016.N().S(`
SELECT user_id,
       tenant_id,
       login,
       COALESCE(display_name, '') AS display_name,
       email_primary,
       COALESCE(locale, '')       AS locale,
       COALESCE(timezone, '')     AS timezone,
       is_active,
       created_at,
       updated_at
FROM users
WHERE login = `)
//line internal/repository/pg/query/user.qtpl:58
	qw422016.E().S(login)
//line internal/repository/pg/query/user.qtpl:58
	qw422016.N().S(`
`)
//line internal/repository/pg/query/user.qtpl:59
}

//line internal/repository/pg/query/user.qtpl:59
func WriteSelectUserByLogin(qq422016 qtio422016.Writer, login string) {
//line internal/repository/pg/query/user.qtpl:59
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/user.qtpl:59
	StreamSelectUserByLogin(qw422016, login)
//line internal/repository/pg/query/user.qtpl:59
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/user.qtpl:59
}

//line internal/repository/pg/query/user.qtpl:59
func SelectUserByLogin(login string) string {
//line internal/repository/pg/query/user.qtpl:59
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/user.qtpl:59
	WriteSelectUserByLogin(qb422016, login)
//line internal/repository/pg/query/user.qtpl:59
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/user.qtpl:59
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/user.qtpl:59
	return qs422016
//line internal/repository/pg/query/user.qtpl:59
}

//line internal/repository/pg/query/user.qtpl:61
func StreamSelectUserByEmail(qw422016 *qt422016.Writer, email string) {
//line internal/repository/pg/query/user.qtpl:61
	qw422016.N().S(`
SELECT user_id,
       tenant_id,
       login,
       COALESCE(display_name, '') AS display_name,
       email_primary,
       COALESCE(locale, '')       AS locale,
       COALESCE(timezone, '')     AS timezone,
       is_active,
       created_at,
       updated_at
FROM users
WHERE email_primary = `)
//line internal/repository/pg/query/user.qtpl:73
	qw422016.E().S(email)
//line internal/repository/pg/query/user.qtpl:73
	qw422016.N().S(`
`)
//line internal/repository/pg/query/user.qtpl:74
}

//line internal/repository/pg/query/user.qtpl:74
func WriteSelectUserByEmail(qq422016 qtio422016.Writer, email string) {
//line internal/repository/pg/query/user.qtpl:74
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/user.qtpl:74
	StreamSelectUserByEmail(qw422016, email)
//line internal/repository/pg/query/user.qtpl:74
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/user.qtpl:74
}

//line internal/repository/pg/query/user.qtpl:74
func SelectUserByEmail(email string) string {
//line internal/repository/pg/query/user.qtpl:74
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/user.qtpl:74
	WriteSelectUserByEmail(qb422016, email)
//line internal/repository/pg/query/user.qtpl:74
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/user.qtpl:74
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/user.qtpl:74
	return qs422016
//line internal/repository/pg/query/user.qtpl:74
}

//line internal/repository/pg/query/user.qtpl:76
func StreamUpdateUser(qw422016 *qt422016.Writer, userID, displayName, locale, timezone string) {
//line internal/repository/pg/query/user.qtpl:76
	qw422016.N().S(`
UPDATE users
SET display_name = `)
//line internal/repository/pg/query/user.qtpl:78
	qw422016.E().S(displayName)
//line internal/repository/pg/query/user.qtpl:78
	qw422016.N().S(`,
    locale       = `)
//line internal/repository/pg/query/user.qtpl:79
	qw422016.E().S(locale)
//line internal/repository/pg/query/user.qtpl:79
	qw422016.N().S(`,
    timezone     = `)
//line internal/repository/pg/query/user.qtpl:80
	qw422016.E().S(timezone)
//line internal/repository/pg/query/user.qtpl:80
	qw422016.N().S(`,
    updated_at   = NOW()
WHERE user_id = `)
//line internal/repository/pg/query/user.qtpl:82
	qw422016.E().S(userID)
//line internal/repository/pg/query/user.qtpl:82
	qw422016.N().S(`
`)
//line internal/repository/pg/query/user.qtpl:83
}

//line internal/repository/pg/query/user.qtpl:83
func WriteUpdateUser(qq422016 qtio422016.Writer, userID, displayName, locale, timezone string) {
//line internal/repository/pg/query/user.qtpl:83
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/user.qtpl:83
	StreamUpdateUser(qw422016, userID, displayName, locale, timezone)
//line internal/repository/pg/query/user.qtpl:83
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/user.qtpl:83
}

//line internal/repository/pg/query/user.qtpl:83
func UpdateUser(userID, displayName, locale, timezone string) string {
//line internal/repository/pg/query/user.qtpl:83
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/user.qtpl:83
	WriteUpdateUser(qb422016, userID, displayName, locale, timezone)
//line internal/repository/pg/query/user.qtpl:83
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/user.qtpl:83
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/user.qtpl:83
	return qs422016
//line internal/repository/pg/query/user.qtpl:83
}

//line internal/repository/pg/query/user.qtpl:85
func StreamSelectUsers(qw422016 *qt422016.Writer, page, pageSize int) {
//line internal/repository/pg/query/user.qtpl:85
	qw422016.N().S(`
SELECT user_id,
       tenant_id,
       login,
       COALESCE(display_name, '') AS display_name,
       email_primary,
       COALESCE(locale, '')       AS locale,
       COALESCE(timezone, '')     AS timezone,
       is_active,
       created_at,
       updated_at
FROM users
ORDER BY created_at DESC
LIMIT `)
//line internal/repository/pg/query/user.qtpl:98
	qw422016.N().D(pageSize)
//line internal/repository/pg/query/user.qtpl:98
	qw422016.N().S(`
OFFSET `)
//line internal/repository/pg/query/user.qtpl:99
	qw422016.N().D((page - 1) * pageSize)
//line internal/repository/pg/query/user.qtpl:99
	qw422016.N().S(`
`)
//line internal/repository/pg/query/user.qtpl:100
}

//line internal/repository/pg/query/user.qtpl:100
func WriteSelectUsers(qq422016 qtio422016.Writer, page, pageSize int) {
//line internal/repository/pg/query/user.qtpl:100
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/user.qtpl:100
	StreamSelectUsers(qw422016, page, pageSize)
//line internal/repository/pg/query/user.qtpl:100
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/user.qtpl:100
}

//line internal/repository/pg/query/user.qtpl:100
func SelectUsers(page, pageSize int) string {
//line internal/repository/pg/query/user.qtpl:100
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/user.qtpl:100
	WriteSelectUsers(qb422016, page, pageSize)
//line internal/repository/pg/query/user.qtpl:100
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/user.qtpl:100
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/user.qtpl:100
	return qs422016
//line internal/repository/pg/query/user.qtpl:100
}

//line internal/repository/pg/query/user.qtpl:102
func StreamCountUsers(qw422016 *qt422016.Writer) {
//line internal/repository/pg/query/user.qtpl:102
	qw422016.N().S(`
SELECT COUNT(*) AS total
FROM users
`)
//line internal/repository/pg/query/user.qtpl:105
}

//line internal/repository/pg/query/user.qtpl:105
func WriteCountUsers(qq422016 qtio422016.Writer) {
//line internal/repository/pg/query/user.qtpl:105
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/repository/pg/query/user.qtpl:105
	StreamCountUsers(qw422016)
//line internal/repository/pg/query/user.qtpl:105
	qt422016.ReleaseWriter(qw422016)
//line internal/repository/pg/query/user.qtpl:105
}

//line internal/repository/pg/query/user.qtpl:105
func CountUsers() string {
//line internal/repository/pg/query/user.qtpl:105
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/repository/pg/query/user.qtpl:105
	WriteCountUsers(qb422016)
//line internal/repository/pg/query/user.qtpl:105
	qs422016 := string(qb422016.B)
//line internal/repository/pg/query/user.qtpl:105
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/repository/pg/query/user.qtpl:105
	return qs422016
//line internal/repository/pg/query/user.qtpl:105
}
